name: flutter_template
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 7.4.0
  dio: 5.1.1
  elementary: 2.0.0
  firebase_crashlytics: 3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  logger: 1.3.0
  path_provider: 2.0.14
  provider: 6.0.5
  retrofit: 4.0.1
  shared_preferences: 2.1.0
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.3.3
  dart_code_metrics: 5.7.2
  elementary_test: 1.1.3
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  mocktail: 0.3.0
  retrofit_generator: 6.0.0+1
  surf_lint_rules: 2.1.0

environment:
  sdk: ">=2.17.0-0 <3.0.0"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
