name: flutter_template
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 7.4.0
  collection: 1.17.1
  dio: 5.1.1
  elementary: 2.0.0
  firebase_crashlytics: 3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 8.0.0
  intl: 0.18.0
  json_annotation: 4.8.1
  logger: 1.3.0
  path: 1.8.3
  path_provider: 2.0.14
  provider: 6.0.5
  retrofit: 4.0.1
  shared_preferences: 2.1.0
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.3.3
  elementary_test: 1.1.3
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  json_serializable: 6.6.1
  mocktail: 0.3.0
  retrofit_generator: 6.0.0+1
  spider: 4.2.1
  surf_lint_rules: 3.0.0

environment:
    sdk: '>=3.0.5 <4.0.0'
    flutter: 3.10.6


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
